version: '3'

services:
  builder:
    build:
      context: .
    image: openwrt-builder
    container_name: openwrt-builder
    environment:
      DEBIAN_FRONTEND: noninteractive
    volumes:
      - ./:/workspace
      - /Volumes/OpenWrt:/openwrt
    stdin_open: true
    ports:
      - "12019:2019"
      - "10081:80"
