#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build amd64 immortalwrt

on:
  push:
    branches:
      - master
    paths:
      - 'prepare.sh'
      - 'post-install.sh'
      - 'amd64.config'
      - 'immortalwrt.config'
      - '.github/workflows/*-amd64-immortalwrt.yml'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  CONFIG_FILE: amd64.config
  PREPARE_SH: prepare.sh
  POST_INSTALL_SH: post-install.sh
  CHECK_CONFIG: true
  SSH_ACTIONS: ${{ secrets.OPENWRT_ENABLE_SSH }}
  OPENWRT_ROOT_PASSWORD: ${{ secrets.OPENWRT_ROOT_PASSWORD }}
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        branch:
        # - openwrt-21.02
        # - v23.05.0-rc3
        - master
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        large-packages: false
        docker-images: false

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E wget -P /usr/local/sbin/ https://github.com/HiGarfield/lede-17.01.4-Mod/raw/master/.github/backup/apt-fast
        sudo -E chmod -R 755 /usr/local/sbin/apt-fast
        sudo -E apt-fast -y -qq install clang-13 dwarves quilt llvm clang lldb lld build-essential rsync asciidoc binutils bzip2 gawk gettext git libncurses5-dev patch python2.7 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx-ucl libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget ccache curl swig libfuse-dev coreutils vim nano python3 python3-dev python3-pip python3-ply python3-pyelftools lrzsz scons
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone --depth 1 $REPO_URL -b ${{ matrix.branch }} openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Fetch openwrt git commit
      id: openwrt-git-commit
      working-directory: /workdir
      run: |
        cd $GITHUB_WORKSPACE/openwrt
        GIT_SHA=$(git rev-parse HEAD)
        echo "openwrt git commit: ${GIT_SHA}"
        echo "sha=${GIT_SHA}" >> $GITHUB_OUTPUT

    - name: Fetch cached git commit else store it
      uses: icyleaf/cloudflare-workers-kv-action@main
      id: cache-git-commit
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      with:
        namespace_id: 85998721d36c4232b1c4939644d3a791
        key: ${{ runner.os }}-immortalwrt-git-commit
        value: ${{ steps.openwrt-git-commit.outputs.sha }}

    - name: Store current git commit
      uses: icyleaf/cloudflare-workers-kv-action@main
      if: steps.openwrt-git-commit.outputs.sha != steps.cache-git-commit.outputs.value
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      with:
        namespace_id: 85998721d36c4232b1c4939644d3a791
        key: ${{ runner.os }}-immortalwrt-git-commit
        value: ${{ steps.openwrt-git-commit.outputs.sha }}
        overwrite: true

    - name: Launching prepare script
      env:
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_USER: ${{ github.actor }}
      run: |
        cd $GITHUB_WORKSPACE/openwrt
        chmod +x $GITHUB_WORKSPACE/$PREPARE_SH
        $GITHUB_WORKSPACE/$PREPARE_SH

    - name: SSH connection to Actions
      uses: mxschmitt/action-tmate@v3
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')

    - name: Use .config file
      run: |
        [ -e $CONFIG_FILE ] && cp $CONFIG_FILE openwrt/.config
        cat immortalwrt.config >> openwrt/.config
        cd $GITHUB_WORKSPACE/openwrt
        make defconfig
        echo "Review .config file"
        cat .config

    - name: Check .config file
      id: check_config
      if: env.CHECK_CONFIG == 'true'
      run: |
        chmod +x check_config.sh
        ./check_config.sh immortalwrt.config
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Download package
      id: package
      run: |
        cd $GITHUB_WORKSPACE/openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
        cd $GITHUB_WORKSPACE/openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/CONFIG_TARGET_(.*)_DEVICE_(.*)=y/\1_\2/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Launching post-install script
      run: |
        chmod +x $POST_INSTALL_SH
        cd $GITHUB_WORKSPACE/openwrt
        $GITHUB_WORKSPACE/$POST_INSTALL_SH

    - name: Upload bin directory
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: ${{ env.FILE_DATE }}_Immortalwrt_${{ env.DEVICE_NAME }}_firmware
        path: openwrt/bin

    - name: Organize files
      id: organize
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd $GITHUB_WORKSPACE/openwrt/bin/targets/*/*
        rm -rf packages
        rm -f immortalwrt-x86-64-generic-squashfs-rootfs.img.gz immortalwrt-x86-64-vmlinuz immortalwrt-x86-64-generic-kernel.bin
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: Immortalwrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Generate release tag
      id: tag
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT

        touch release.txt
        echo "VERSION: $RELEASE_TAG (Immortalwrt-YYYYmmdd_HHMMSS_Immortalwrt-GIT-REF)" >> release.txt
        echo "REPO: $REPO_URL/tree/$REPO_BRANCH" >> release.txt
        echo "CONFIG_FILE: $CONFIG_FILE" >> release.txt

        echo "Changelogs: " >> release.txt
        SHA_VALUE=${{ steps.cache-git-commit.outputs.value }}
        if [[ -z "$SHA_VALUE" ]]; then
          SHA_VALUE=${{ steps.openwrt-git-commit.outputs.sha }}
        fi
        echo "${REPO_URL}/compare/${SHA_VALUE}...${{ steps.openwrt-git-commit.outputs.sha }}" >> release.txt

        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware to release
      id: upload-firmware
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ matrix.branch }}-${{ env.RELEASE_TAG }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*
